### ISSUE TITLE
Make json2ts_cmd platform independent

### ISSUE THREAD

**Issue by saschahofmann** [phillipdupuis/pydantic-to-typescript#25]
We are using yarn as our package manager hence we need to run `yarn json2ts` to run the command. I don't think I want to add **json2ts** to the global path (I think that wouldn't be a great idea for a reproducible repo?) so I have to provide the path to executable which works. 

The only problem is that this path can change locally especially if someone (like silly me for the next few days) has to work on windows. 

I was playing around with it and you can provide `yarn json2ts` to `os.system` but unfortunately `shutil.which` fails in line 189 in script.py. Maybe we could remove that check all together? Or am I missing a simple setup step to add json2ts consistently?

Happy to submit something once I am clear what should be done.

**Comment by phillipdupuis** [comment]
Ooh, well that is annoying... a 'safety check' which actually causes problems instead of preventing them. 🤔 

I think you're right that the `shutil.which` check should not result in an error. 
At most it should be a warning (so you at least have some guidance in STDOUT if things go wrong).

I think we'll be in a good place if I change it from an exception to a warning and merge this PR for checking the os.system call exit code (https://github.com/phillipdupuis/pydantic-to-typescript/pull/14/commits/f2230e8461fd238753c38cfc75eeb1a2e1212d45).

I'll do that tomorrow.  Hoping you don't need to do any more work until Monday 🤞

**Comment by phillipdupuis** [comment]
This should be fixed with release 1.0.10, but let me know if you encounter any issues

**Comment by saschahofmann** [comment]
That was fast! Thank you!
