### ISSUE TITLE
Repeat executions use cached module

### ISSUE THREAD

**Issue by captaincoordinates** [phillipdupuis/pydantic-to-typescript#7]
I'm calling `generate_typescript_defs` repeatedly within a Python script in response to file changes (via watchdog). The goal is to have any changes to my Pydantic models automatically propagated to their TypeScript counterparts, which will then cause a "watch" build (e.g. Angular's `ng serve`) to highlight all TypeScript references that require update. 

Watchdog is correctly executing `generate_typescript_defs` in response to each Pydantic model change, but pydantic2ts appears to use a cache of the module acquired during its first run. No matter how I change the Pydantic model the generated TypeScript is always the same, until I kill the process and restart. Is there any way I can force pydantic2ts to reload the module each time `generate_typescript_defs` is called, without starting a new Python process each time?

My module references are in the dot-separated format, not file paths, and looking at the source for `import_module` I had hoped to simply call `importlib.reload(module)` prior to each call to `generate_typescript_defs`, but this did not make a difference. Any suggestions would be very much appreciated.

**Comment by phillipdupuis** [comment]
Ahh this is a really cool use case! I like it. I'll write some tests to try and figure out if I can figure out a clean way to optionally reload modules each time

That said, one solution that might work now would be to have `generate_typescript_defs` use a fresh interpreter each time.  I know you said you'd like to avoid starting a new python process each time, but I'm assuming that was in reference to the watchdog process? (correct me if I'm wrong)

If you'd like to try that, I think calling this instead of generate_typescript_defs may work:
```python
from multiprocessing import Process

def run_pydantic2ts(module, output):
    p = Process(target=generate_typescript_defs, args=(module, output))
    p.start()
    p.join()
```
